name: Run Python Script Daily

on:
  push:
  schedule:
    - cron: '0 * * * *'



jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      id: run_script
      run: |
            echo "SCRIPT_OUTPUT=$(python main.py | tail -n 1)" >> $GITHUB_ENV
      env:
        API_URL: ${{ secrets.API_URL }}

    - name: Send Discord notification if housingRentalObjects are available
      if: env.SCRIPT_OUTPUT == 'HOUSING_RENTAL_OBJECTS_AVAILABLE'
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'Housing rental objects are now available!'

    - name: Send Discord notification if no housingRentalObjects are available
      if: env.SCRIPT_OUTPUT == 'NO_HOUSING_RENTAL_OBJECTS_AVAILABLE'
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: 'No housing rental objects at this time.'
